services:
  frontend:
    build:
      context: .
      dockerfile: compose/Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL}
        VITE_VAPID_PUBLIC_KEY: ${VITE_VAPID_PUBLIC_KEY}
    env_file: .env
    container_name: msg-frontend
    networks:
      - messaging-gateway_default
    restart: unless-stopped
    ports:
      - "8080:80"

networks:
  messaging-gateway_default:
    external: true
